name: wheeled_model
channels:
  - aihabitat
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - cmake=3.27
  - numpy
  - pandas
  - opencv
  - quaternion
  - onnx
  - onnxruntime
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - habitat-sim=0.3.3=*_bullet_*